cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2025.11.2
  api_framework: drf
  author_name: Alde
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  database: postgres
  deploy_platform: fly
  description: SaaS Hospital Management
  docker_mode: full
  docker_setup: default
  domain_name: localhost:8000
  email: aldesabidoworker@gmail.com
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: react
  github_username: tobitaks
  include_static_files: n
  marketing_email_platform: none
  plugins:
  - chat
  post_process: y
  project_name: Dash Hospital Mngt
  project_slug: dash_hospital_mngt
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  type_checker: none
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_agents: y
  use_ai_rules_claude: y
  use_ai_rules_cursor: y
  use_ai_rules_junie: n
  use_api_auth: y
  use_api_keys: y
  use_async: y
  use_auto_reload: n
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: n
  use_debug_toolbar: n
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
  use_watchfiles: n
